services:
  - type: web
    name: multitenant-crm-backend
    env: node
    plan: free
         buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    preDeployCommand: npm run migration:run && npm run setup:db
    envVars:
      - key: NODE_ENV
        value: production
             - key: DATABASE_HOST
         fromDatabase:
           name: multitenant-crm-postgres
           property: host
       - key: DATABASE_PORT
         fromDatabase:
           name: multitenant-crm-postgres
           property: port
       - key: DATABASE_NAME
         fromDatabase:
           name: multitenant-crm-postgres
           property: database
       - key: DATABASE_USERNAME
         fromDatabase:
           name: multitenant-crm-postgres
           property: username
       - key: DATABASE_PASSWORD
         fromDatabase:
           name: multitenant-crm-postgres
           property: password
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: multitenant-crm-postgres
    databaseName: multitenant_crm
    user: multitenant_user
    plan: free
